#!/bin/bash

source MonitorConfiguration

primXrandr="--output $primMon --primary --mode 2560x1440 --pos 1920x0 --rotate normal --rate 144 --set TearFree on"
secXrandr="--output $secMon --mode 1920x1080 --pos 0x180 --rotate normal --rate 144 --set TearFree on" 
miniXrandr="--output $miniMon --mode 1280x720 --pos 4480x1386 --rotate normal --set TearFree off"

cp /home/dan/Pictures/wallpaper/3monnormal.png /home/dan/Pictures/wallpaper/wall.png
xrandr $primXrandr $secXrandr $miniXrandr
sleep .5
nitrogen --set-auto /home/dan/Pictures/wallpaper/3monnormal.png
xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput $primMon