#!/bin/bash
# A script to toggle the orientation of my secondary monitor. Will maintain the state of the mini monitor

if [ $(xrandr --prop | grep 'HDMI-A-0' | cut -d ' ' -f 3) = "(normal" ]; then
	if [ $(xrandr --prop | grep 'DisplayPort-2' | cut -d ' ' -f 4) = "left" ]; then
		set2MonOrientationNormal
	else
		set2MonOrientationLeft
	fi
else
	if [ $(xrandr --prop | grep 'DisplayPort-2' | cut -d ' ' -f 4) = "left" ]; then
		set3MonOrientationNormal
	else
		set3MonOrientationLeft
	fi
fi
